In [1]:
# Import necessary libraries for data manipulation, machine learning models, and metrics
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [2]:
# Load the preprocessed weather dataset
nome_file = "./weather_clf_reg_preprocessed.csv"
df = pd.read_csv(nome_file)

df

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,...,WindGustDir_sin,WindGustDir_cos,WindDir9am_sin,WindDir9am_cos,WindDir3pm_sin,WindDir3pm_cos,Day,Year,Latitude,Longitude
0,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,1007.1,...,-1.000000,-1.836970e-16,-1.000000,-1.836970e-16,-0.923880,3.826834e-01,336,2008,-36.0737,146.9135
1,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,1007.8,...,-0.923880,3.826834e-01,-0.382683,9.238795e-01,-0.923880,-3.826834e-01,337,2008,-36.0737,146.9135
2,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.0,1007.6,1008.7,...,-0.923880,-3.826834e-01,-1.000000,-1.836970e-16,-0.923880,-3.826834e-01,338,2008,-36.0737,146.9135
3,9.2,28.0,0.0,24.0,11.0,9.0,45.0,16.0,1017.6,1012.8,...,0.707107,7.071068e-01,0.707107,-7.071068e-01,1.000000,6.123234e-17,339,2008,-36.0737,146.9135
4,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,1006.0,...,-1.000000,-1.836970e-16,0.923880,3.826834e-01,-0.707107,7.071068e-01,340,2008,-36.0737,146.9135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140780,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,1021.2,...,1.000000,6.123234e-17,0.923880,-3.826834e-01,1.000000,6.123234e-17,171,2017,-25.3444,131.0369
140781,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,1020.3,...,1.000000,6.123234e-17,0.707107,-7.071068e-01,0.923880,3.826834e-01,172,2017,-25.3444,131.0369
140782,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,1019.1,...,-0.382683,9.238795e-01,0.707107,-7.071068e-01,0.000000,1.000000e+00,173,2017,-25.3444,131.0369
140783,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,1016.8,...,0.000000,1.000000e+00,0.707107,-7.071068e-01,-0.923880,3.826834e-01,174,2017,-25.3444,131.0369
140784,7.8,27.0,0.0,28.0,13.0,7.0,51.0,24.0,1019.4,1016.5,...,0.707107,-7.071068e-01,0.382683,-9.238795e-01,0.000000,1.000000e+00,175,2017,-25.3444,131.0369

Preparazione dati

In [3]:
# Separate features (X) and target variable (y)
X = df.drop(columns=["RainfallTomorrow"])
y = df["RainfallTomorrow"]

In [4]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X_train

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,...,WindGustDir_sin,WindGustDir_cos,WindDir9am_sin,WindDir9am_cos,WindDir3pm_sin,WindDir3pm_cos,Day,Year,Latitude,Longitude
94016,14.4,30.0,0.0,33.000000,9.0,20.000000,48.0,36.00000,1018.60000,1015.100000,...,0.923880,-0.382683,-0.707107,0.707107,-0.923880,-0.382683,15,2012,-34.9285,138.6007
90638,24.1,29.6,0.0,31.000000,4.0,15.000000,77.0,87.00000,1013.20000,1010.300000,...,0.923880,0.382683,0.707107,0.707107,0.382683,0.923880,90,2011,-19.2590,146.8169
117720,15.9,29.2,0.0,46.000000,9.0,20.000000,53.0,43.00000,1015.90000,1011.000000,...,-0.707107,-0.707107,0.923880,-0.382683,-0.707107,-0.707107,58,2012,-31.9522,115.8589
81232,13.0,26.8,1.0,43.000000,9.0,19.000000,61.0,58.00000,1017.60000,1010.800000,...,0.000000,1.000000,0.707107,0.707107,0.382683,0.923880,285,2009,-27.4698,153.0251
81245,16.7,28.9,0.4,46.000000,6.0,19.000000,56.0,57.00000,1015.60000,1011.500000,...,-0.707107,-0.707107,0.707107,-0.707107,0.382683,0.923880,298,2009,-27.4698,153.0251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39696,6.2,20.2,8.4,24.000000,7.0,7.000000,89.0,63.00000,1028.50000,1024.500000,...,0.923880,0.382683,-0.923880,0.382683,0.707107,0.707107,160,2013,-32.7933,151.8367
3219,3.3,27.1,0.0,70.000000,11.0,31.000000,69.0,23.00000,1009.40000,1001.900000,...,-0.707107,0.707107,0.000000,1.000000,-0.707107,0.707107,233,2009,-33.8967,150.7503
17087,16.5,24.2,0.0,56.677816,0.0,38.054628,62.0,41.52959,1007.55587,1003.998976,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,103,2016,-32.9167,151.7500
109802,12.7,18.1,0.0,39.000000,20.0,19.000000,85.0,67.00000,1020.00000,1018.400000,...,-0.707107,-0.707107,-0.923880,-0.382683,-0.707107,-0.707107,284,2014,-34.0278,115.1000
28402,6.4,19.0,0.2,15.000000,4.0,6.000000,99.0,50.00000,1025.70000,1021.900000,...,0.382683,0.923880,0.707107,-0.707107,0.382683,0.923880,147,2015,-33.6000,150.7833

In [ ]:
# Standardize the numerical features by removing the mean and scaling to unit variance
scaler = StandardScaler().set_output(transform="pandas")
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22
0,0.344003,0.949957,-0.276968,-0.521781,-0.563550,0.137766,-1.088936,-0.743954,0.174482,0.017266,...,1.365941,-0.499711,-1.084006,1.002896,-1.290525,-0.489264,-1.571690,-0.299472,-0.361500,-0.287093
1,1.859323,0.893728,-0.276968,-0.671684,-1.126654,-0.426585,0.427384,1.720275,-0.594565,-0.671362,...,1.365941,0.630374,1.027539,1.002896,0.570301,1.399918,-0.855465,-0.692890,2.226117,0.392943
2,0.578331,0.837498,-0.276968,0.452588,-0.563550,0.137766,-0.827502,-0.405726,-0.210041,-0.570938,...,-1.002608,-0.978731,1.351200,-0.566588,-0.981794,-0.958354,-1.161054,-0.299472,0.129998,-2.169378
3,0.125297,0.500122,-0.159153,0.227733,-0.563550,0.024896,-0.409206,0.319047,0.032066,-0.599630,...,0.024266,1.541859,1.027539,1.002896,0.570301,1.399918,1.006723,-1.479727,0.870209,0.906781
4,0.703306,0.795326,-0.229842,0.452588,-0.901412,0.024896,-0.670641,0.270729,-0.252766,-0.499205,...,-1.002608,-0.978731,1.027539,-1.033814,0.570301,1.399918,1.130868,-1.479727,0.870209,0.906781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112623,-0.936988,-0.427663,0.712677,-1.196344,-0.788792,-1.329548,1.054827,0.560638,1.584400,1.365830,...,1.365941,0.630374,-1.407666,0.535671,1.032350,1.086482,-0.186987,0.093946,-0.008899,0.808420
112624,-1.390022,0.542294,-0.276968,2.251423,-0.338308,1.379340,0.009089,-1.372090,-1.135745,-1.876462,...,-1.002608,1.109394,-0.028233,1.424712,-0.981794,1.086482,0.510139,-1.479727,-0.191111,0.718501
112625,0.672062,0.134631,-0.276968,1.252906,-1.577137,2.175598,-0.356919,-0.476774,-1.398379,-1.575334,...,0.024266,0.065332,-0.028233,-0.015459,0.025278,0.064064,-0.731319,1.274201,-0.029277,0.801244
112626,0.078432,-0.722867,-0.276968,-0.072072,0.675279,0.024896,0.845680,0.753911,0.373864,0.490698,...,-1.002608,-0.978731,-1.407666,-0.566588,-0.981794,-0.958354,0.997173,0.487365,-0.212761,-2.232190
112627,-0.905745,-0.596351,-0.253405,-1.870907,-1.126654,-1.442418,1.577697,-0.067499,1.185635,0.992823,...,0.580006,1.429465,1.027539,-1.033814,0.570301,1.399918,-0.311133,0.880783,-0.142115,0.721232

Regressore Unico

In [8]:
# Perform Grid Search Cross-Validation to find the best hyperparameters for the general Random Forest Regressor
search_reg = RandomForestRegressor()

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, None],
}

grid_search = GridSearchCV(search_reg, param_grid, cv=5, n_jobs = -1)
grid_search.fit(X_train, y_train)

print("Risultati medi per tutte le combinazioni:", grid_search.cv_results_["mean_test_score"])
print("Migliori parametri trovati:", grid_search.best_params_)
print("Punteggio migliore:", grid_search.best_score_)

Risultati medi per tutte le combinazioni: [0.31492474 0.31597388 0.32438402 0.32881457]
Migliori parametri trovati: {'max_depth': None, 'n_estimators': 200}
Punteggio migliore: 0.32881457080475884

In [12]:
# Train a Random Forest Regressor using a specific set of parameters
reg1 = RandomForestRegressor(max_depth = None, n_estimators = 200, n_jobs= -1)
reg1.fit(X_train, y_train)
y_pred1 = reg1.predict(X_test)

In [13]:
# Evaluate the regressor performance (R^2 score and MAE)
print(reg1.score(X_test, y_test))
print(mean_absolute_error(y_pred1, y_test))

0.37120603121085893
2.429958660368647

Classificatore + Regressore

In [14]:
# Dati per allenare il classificatore
X_clf = X_train
y_clf = (y_train > 0)

In [15]:
# Dati per allenare il regressore
X_reg = X_train[y_clf]
y_reg = y_train[y_clf]

Classificatore

In [ ]:
# Perform Grid Search to find best parameters for the Classifier
search_clf = RandomForestClassifier()

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, None],
}

grid_search = GridSearchCV(search_clf, param_grid, cv=5, n_jobs = -1)
grid_search.fit(X_clf, y_clf)

print("Risultati medi per tutte le combinazioni:", grid_search.cv_results_["mean_test_score"])
print("Migliori parametri trovati:", grid_search.best_params_)
print("Punteggio migliore:", grid_search.best_score_)

Risultati medi per tutte le combinazioni: [0.79648931 0.79732391 0.80677094 0.80848455]
Migliori parametri trovati: {'max_depth': None, 'n_estimators': 200}
Punteggio migliore: 0.808484554782078

Regressore

In [ ]:
# Perform Grid Search to find best parameters for the Regressor (on filtered data)
search_reg = RandomForestRegressor()

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, None],
}

grid_search = GridSearchCV(search_reg, param_grid, cv=5, n_jobs = -1)
grid_search.fit(X_reg, y_reg)

print("Risultati medi per tutte le combinazioni:", grid_search.cv_results_["mean_test_score"])
print("Migliori parametri trovati:", grid_search.best_params_)
print("Punteggio migliore:", grid_search.best_score_)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Risultati medi per tutte le combinazioni: [0.26188512 0.26795061 0.27140803 0.27767874]
Migliori parametri trovati: {'max_depth': None, 'n_estimators': 200}
Punteggio migliore: 0.2776787361575438

Allenamento classificatore e regressore con i migliori parametri trovati

In [18]:
# Train the Classifier with best parameters found
clf = RandomForestClassifier(max_depth = None, n_estimators = 200, n_jobs = -1)
reg = RandomForestRegressor(max_depth = None, n_estimators = 200, n_jobs= -1)
clf.fit(X_clf, y_clf)
reg.fit(X_reg, y_reg)

RandomForestRegressor(n_estimators=200, n_jobs=-1)

Testing

In [19]:
# Predict if it will rain, then predict the rain amount only for predicted rainy days
y_pred_clf = clf.predict(X_test)
y_pred_reg = reg.predict(X_test)
y_pred2 = [0 if c==0 else r for (c, r) in zip(y_pred_clf, y_pred_reg)]

In [20]:
print(mean_absolute_error(y_pred2, y_test))

2.2504581276414393

Confronto risultati

In [ ]:
# MAE
print(mean_absolute_error(y_pred1, y_test), mean_absolute_error(y_pred2, y_test))

# MSE
print(mean_squared_error(y_pred1, y_test), mean_squared_error(y_pred2, y_test))

# Accuracy
y_pred1_int = [int(e) for e in y_pred1]
y_pred2_int = [int(e) for e in y_pred2]
print(sum(y_pred1_int==y_test)/len(y_test), sum(y_pred2_int==y_test)/len(y_test))

2.429958660368647 2.2504581276414393
43.63888129628511 44.4949242251394
0.4766132755620272 0.590155201193309